CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 15
CAMERA_FLIP = True

BUZZER_GPIO = 18

ALARM_TIME = 0.8
ALARM_LEVEL2_TIME = 2.5
ALARM_LEVEL3_TIME = 99.0

DRIVER_STATE_FRAME_HEIGHT = 480
PERCLOS_WINDOW_SECONDS = 20

APP_NAME = "MFI Driver Monitoring System"
WINDOW_NAME = "MFI DMS"

SPLASH_IMAGE = "assets/mfi_splash.png"
SPLASH_TIME_MS = 2500
